Feat/#107 driver self order
softeerbootcamp-3rd/Team4-HansalChai pull request #122
Opened 2024-02-17 09:24 UTC by sjmjys954646

## 반영 브랜치
Feat/#107 driver self order -> BE_dev

## PR 요약
- driver 본인이 승인한 요청 확인
- driver 본인이 승인한 요청 세부 정보 확인

## PR 설명
- Trifunction, Enum활용해서 깔끔하게 짠것 같은데 테스트 할려면 인증 필요해서 프론트 작업하라고 일단 api만 먼저 올려놓습니다.

2024-02-17 11:31 UTC, jiaeYoon requested changes
리뷰 확인하시고 답변 및 반영 부탁드립니다~

2024-02-17 11:31 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
> +	public ResponseEntity<ApiResponse<OrderDTO>> getMyOrder(@RequestParam(value = "keyword", defaultValue = "배송 전") String keyword, @RequestParam(value = "page", defaultValue = "0") int page, HttpServle
keyword를 '배송 전'보단 'NOT_STARTED', 'IN_PROGRESS', 'DONE' 이렇게 받는 게 더 편하지 않을까요?

2024-02-17 11:31 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderResponse.java
costCut(), getDateTiemToString()은 중복되기도 하고 다른 클래스에도 필요한 클래스니까 다음과 같이 Util 클래스로 만들어서 사용하는거 어떠신가요?
```java
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class ReservationUtil {

	public static String dateTimeToString(LocalDate date, LocalTime time) {
		return date.toString() + " " + time.toString();
	}

	public static int cutCost(int fee) {
		return fee / 10000;
	}
}
```

2024-02-17 11:31 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
> +		Page<Reservation> pageContent = OrderStatusCategory.valueOf(keyword).execute(user.getUserId(), pageable, reservationRepository);
valueOf는 "BEFORE_DELIVERY" 문자열을 줬을 때 OrderStatusCategory 타입의 BEFORE_DELIVERY 상수를 리턴하는 것으로 알고있습니다. valueOf("배송 전")을 실행하면 에러가 발생할 것 같습니다!

2024-02-17 11:31 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
> +	Page<Reservation> findByDriverIdAfterDelivery(@Param("userId")Long id, Pageable pageable);
의미를 명확히 하려고 메소드를 분리하신건가요? 
그게 아니라면 `@Param(transportStatus) String transportStatus` 를 사용해서 반복되는 쿼리를 줄일 수 있을 것 같습니다.

2024-02-17 11:31 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
> +	public ResponseEntity<ApiResponse<OrderDetailDTO>> getMyOrderDetauk(@PathVariable("id")Long id, HttpServletRequest request){
메서드 명에 오타있습니다!

2024-02-17 11:31 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderResponse.java
> +				.build();
피그마엔 없지만 출발지와 목적지에 상세 주소도 필요해보입니다

2024-02-17 12:01 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
> +		boolean isLastPage = pageContent.getNumberOfElements() < PAGECUT;
전체 예약이 10개고 페이지 크기가 10인 경우, 해당 페이지가 마지막 페이지가 됩니다. 그래서 부등호를 `<` 에서 `<=`로 바꿔야 할 것 같아요

2024-02-17 12:48 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
> +	public ResponseEntity<ApiResponse<OrderDTO>> getMyOrder(@RequestParam(value = "keyword", defaultValue = "배송 전") String keyword, @RequestParam(value = "page", defaultValue = "0") int page, HttpServle
프론트쪽에서 사용하는 문자열로 받는게 편할것같아서 이렇게 했습니다.

2024-02-17 12:49 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderResponse.java
이 부분 추후에 리팩토링 예정입니다.

2024-02-17 12:51 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
> +		Page<Reservation> pageContent = OrderStatusCategory.valueOf(keyword).execute(user.getUserId(), pageable, reservationRepository);
valueOf거친 enum형에 대한 실행이라 괜찮을것같습니다

2024-02-17 12:51 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
> +	Page<Reservation> findByDriverIdAfterDelivery(@Param("userId")Long id, Pageable pageable);
명확히 하려한거긴 한데 추후에 확인해보죠

2024-02-18 00:47 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
> +	public ResponseEntity<ApiResponse<OrderDetailDTO>> getMyOrderDetauk(@PathVariable("id")Long id, HttpServletRequest request){
해결했습니다.

2024-02-18 00:47 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
> +		Page<Reservation> pageContent = OrderStatusCategory.valueOf(keyword).execute(user.getUserId(), pageable, reservationRepository);
수정했습니다.

2024-02-18 00:47 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
> +		boolean isLastPage = pageContent.getNumberOfElements() < PAGECUT;
수정했습니다.

2024-02-18 01:32 UTC, jiaeYoon approved these changes
수고 많으셨습니다

2024-02-18 02:03 UTC, jiaeYoon approved these changes
수고 많으셨습니다~

2024-02-18 02:03 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderResponse.java
> +				.build();
디미터의 법칙 위반..이지만 나중에 리팩토링하죠

2024-02-18 02:06 UTC, merged