Feature/#18 reservation
softeerbootcamp-3rd/Team4-HansalChai pull request #33
Opened 2024-02-08 02:52 UTC by sjmjys954646

feat/#18-reservation -> BE_dev

## PR 요약
- reservation에 필요한 entity들 생성
- 화물 가격 처리 알고리즘 개발

## PR 설명
- entity에는 @column(nullable = false) DTO에는 Valid어노테이션
- 화물 가격표를 생성후 lower_bound로 탐색후 가격비교후 return
- requestDTO처리

2024-02-08 05:18 UTC, jiaeYoon requested changes
리뷰 확인하시고 반영 부탁드립니다

2024-02-08 05:18 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
> +	private TransportStatus state = TransportStatus.NOT_STARTED;
변수명을 클래스 이름과 비슷하게 status로 바꿔주세요

2024-02-08 05:18 UTC, jiaeYoon commented on haul-be/src/test/java/com/hansalchai/haul/common/utils/CargoFeeTableTest.java
BDD 방식을 제안합니다. print 대신 assertThat을 써봅시다.

2024-02-08 05:18 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Reservation.java
> +	private int reservationId;
id의 타입을 Long으로 바꾸는거 어떨까요?

2024-02-08 07:45 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationRestController.java
> +	public ResponseEntity<?> customerReservation(
`ResponseEntity<ApiResponse<ReservationResponse.ReservationRecommendationDTO>>` 로 수정하였습니다.

2024-02-08 07:45 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationRequest.java
> +		private CargoOptionDTO cargoOption;
호눅스님 같았어요

<img width="229" alt="스크린샷 2024-02-08 오후 4 41 39" src="https://github.com/softeerbootcamp-3rd/Team4-HansalChai/assets/37840237/1ae47700-6026-443f-9761-dce91ca501dd">

2024-02-08 07:45 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationRequest.java
> +	@Setter
Setter대신 Builder를 썼습니다.

2024-02-08 07:45 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Destination.java
> +
변경하였습니다.

2024-02-08 07:45 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Reservation.java
> +	private int reservationId;
변경하였습니다.

2024-02-08 07:45 UTC, sjmjys954646 commented on haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
> +	private TransportStatus state = TransportStatus.NOT_STARTED;
변경하였습니다.

2024-02-09 11:09 UTC, jiaeYoon requested changes
리뷰 확인하시고 의견 있으시면 남겨주세요

추가적으로 엔티티의 id 값은 전부 Long 타입으로 바꾸는거 어떨까요?
하이버네이트에서 id 값은 wrapper type으로 선언하길 권장한다고 합니다. 관련 링크도 같이 첨부합니다(https://hyune-c.tistory.com/44)

2024-02-12 02:01 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/owner/entity/Owner.java
> +	private Driver driver;
Car가 차에 대한 정보고 Owner가 실질 차량이니까 Driver-Owner는 1:n이 맞네요

2024-02-12 02:04 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/common/utils/CarCategorySelector.java
> +			return CarCategory.IS_BOXTRUCK;
탑차는 무조건 냉동, 냉장이 가능 했었나요?

2024-02-12 02:08 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
> +		reservationRepository.save(reservation);
CASCADE쓰면 Reservation만 저장해도 관련된 엔티티도 모두 함께 저장되는 걸로 알고 있습니다. 이 링크 보시면 좋을 것 같아요(https://zzang9ha.tistory.com/350)

2024-02-12 02:13 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
> +	public ReservationResponse.ReservationRecommendationDTO createReservation(ReservationRequest.CreateReservationDTO request) {
예약 생성 메서드는 항상 null을 반환하나요?

2024-02-12 02:29 UTC, jiaeYoon approved these changes
수고많으셨습니다!

2024-02-12 02:29 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
> +				.append(reservation.getCar().getLength());
reservation.getCar().getSizeToString() 같은 메서드로 문자열을 생성해봐도 좋을 것 같습니다

2024-02-12 06:27 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomCarRepositoryImpl.java
> +public class CustomCarRepositoryImpl implements CustomCarRepository {
findProperCar 메서드가 변경될 가능성이 있어서 인터페이스를 implements하는 방식을 선택하신 건가요?

2024-02-12 14:27 UTC, jiaeYoon approved these changes
수고 많으셨습니다!
저희 Customer, Driver 엔티티를 User로 변경했으니 그것도 반영해봅시다

2024-02-12 14:27 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/common/utils/BaseTime.java
>  	private LocalDateTime createdAt;
nullable 옵션 제거하신 이유가 있을까요?

2024-02-12 14:27 UTC, jiaeYoon commented on haul-be/src/main/java/com/hansalchai/haul/common/utils/CarCategorySelector.java
> +			return CarCategory.DEFAULT;
냉장, 냉동 둘 다 가능하면 내장 탑차인가요?

2024-02-12 14:27 UTC, jiaeYoon commented on haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
> +		logger.info(String.valueOf(reservationRecommendationDTO.getCar().getModel()));
assertions.assertthat 쓰시면 테스트 코드 이해하기 더 쉬워질 것 같습니다!

2024-02-13 01:12 UTC, merged